parameters:
    ongr_oxid.modifier.category.class: ONGR\OXIDConnectorBundle\Modifier\CategoryModifier

services:
    ongr_oxid.modifier.category:
        class: %ongr_oxid.modifier.category.class%
        tags:
            - { name: 'ongr_connections.doctrine.modifier', type: 'category' }

    ongr_oxid.modifier.category_seo:
        parent: ongr_oxid.modifier.seo
        tags:
            - { name: 'ongr_connections.doctrine.modifier', type: 'category' }

    ongr_oxid.modifier.category_seo_url:
        parent: ongr_oxid.modifier.seo_url
        tags:
            - { name: 'ongr_connections.doctrine.modifier', type: 'category' }
