parameters:
    ongr_oxid.modifier.content.class: ONGR\OXIDConnectorBundle\Modifier\ContentModifier

services:
    ongr_oxid.modifier.content:
        class: %ongr_oxid.modifier.content.class%
        calls:
           - [ setLanguageId, [%ongr_oxid.language_id%] ]
        tags:
            - { name: 'kernel.event_listener', event: ongr.pipeline.import.default.modify, method: onModify }
