parameters:
    ongr_oxid.modifier.content.class: ONGR\OXIDConnectorBundle\Modifier\ContentModifier

services:
    ongr_oxid.modifier.content:
        class: %ongr_oxid.modifier.content.class%
        arguments: [ "@ongr_oxid.attr_to_doc_service" ]
        tags:
            - { name: 'kernel.event_listener', event: ongr.pipeline.import.default.modify, method: onModify }

    ongr_oxid.modifier.content_seo:
        parent: ongr_oxid.modifier.seo
        tags:
            - { name: 'ongr_connections.doctrine.modifier', type: 'content' }

    ongr_oxid.modifier.content_seo_url:
        parent: ongr_oxid.modifier.seo_url
        tags:
            - { name: 'ongr_connections.doctrine.modifier', type: 'content' }
