parameters:
    ongr_oxid.modifier.product.class: ONGR\OXIDConnectorBundle\Modifier\ProductModifier

services:
    ongr_oxid.modifier.product:
        class: %ongr_oxid.modifier.product.class%
        arguments: [ "@ongr_oxid.attr_to_doc_service" ]
        calls:
           - [ setLanguageId, [%ongr_oxid.language_id%] ]
        tags:
            - { name: 'kernel.event_listener', event: ongr.pipeline.import.default.modify, method: onModify }
