parameters:
    ongr_oxid.seo_url_service.class: ONGR\OXIDConnectorBundle\Service\SeoUrlService

services:
    ongr_oxid.seo_url_service:
        class: %ongr_oxid.seo_url_service.class%
        arguments:
            - @doctrine.orm.default_entity_manager
        calls:
            - [setEntityAlias, [%ongr_oxid.entity_namespace%]]
            - [setShopId, [%ongr_oxid.shop_id%]]
            - [setLanguageId, [%ongr_oxid.language_id%]]
