parameters:
    ongr_oxid.modifier.seo.class: ONGR\OXIDConnectorBundle\Modifier\SeoModifier
    ongr_oxid.modifier.seo_url.class: ONGR\OXIDConnectorBundle\Modifier\SeoUrlModifier
    ongr_oxid.seo_url_service.class: ONGR\OXIDConnectorBundle\Service\SeoUrlService

services:
    ongr_oxid.seo_url_service:
        class: %ongr_oxid.seo_url_service.class%
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [setEntityAlias, [%ongr_oxid.entity_namespace%]]
            - [setShopId, [%ongr_oxid.shop_id%]]
            - [setLanguageId, [%ongr_oxid.language_id%]]

    ongr_oxid.modifier.seo:
        class: %ongr_oxid.modifier.seo.class%
        abstract: true
        arguments:
            - @doctrine.orm.entity_manager
        calls:
            - [setEntityAlias, [%ongr_oxid.entity_namespace%]]
            - [setShopId, [%ongr_oxid.shop_id%]]
            - [setLanguageId, [%ongr_oxid.language_id%]]

    ongr_oxid.modifier.seo_url:
        class: %ongr_oxid.modifier.seo_url.class%
        abstract: true
        arguments:
            - @ongr_oxid.seo_url_service
