parameters:
    ongr_oxid.mapping_listener.class: ONGR\ConnectionsBundle\EventListener\LoadClassMetadataListener
    ongr_oxid.attributes_to_documents_service.class: ONGR\OXIDConnectorBundle\Service\AttributesToDocumentsService

    ongr_oxid.triggers.seo_trigger.class: ONGR\OXIDConnectorBundle\Trigger\SeoTrigger

services:
    ongr_oxid.attr_to_doc_service:
        class: %ongr_oxid.attributes_to_documents_service.class%
