language: php
php:
  - 5.4
  - 5.5
env:
  - SYMFONY="2.3.*" # LTS version
  - SYMFONY="2.5.*" # Latest version
install:
  - composer require symfony/symfony:${SYMFONY}
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs -p --standard=$TRAVIS_BUILD_DIR/vendor/ongr/ongr-strict-standard/ONGR --ignore=vendor/,Tests/app/,Resources/public/ ./
