parameters:
    ongr_oxid.relations.content.track_fields:
      - OXTITLE
      - OXCONTENT
      - OXFOLDER
      - OXLOADID

services:
    # Content relations
    ongr_oxid.relations.oxcontent_insert:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxcontents, C, NEW.OXID, 1, content]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: oxcontent_insert }

    ongr_oxid.relations.oxcontent_update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxcontents, U, NEW.OXID, 1, content, %ongr_oxid.relations.content.track_fields%]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: oxcontent_update }

    ongr_oxid.relations.oxcontent_delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxcontents, D, OLD.OXID, 1, content]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: oxcontent_delete }
