parameters:
    ongr_oxid.relations.actions_article.track_fields:
      - OXACTIONID
      - OXARTID
      - OXSORT

services:
    ongr_oxid.relations.actions_article.create:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxactions2article, C, 1, product, NEW.OXARTID, [], U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: actions_article_create }

    ongr_oxid.relations.actions_article.update:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxactions2article, U, 1, product, NEW.OXARTID, %ongr_oxid.relations.actions_article.track_fields%, U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: actions_article_update }
        calls:
            - [addStatement, [ @ongr_oxid.relations.actions_article_old.update ] ]

    ongr_oxid.relations.actions_article.delete:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxactions2article, D, 1, product, OLD.OXARTID, [], U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: actions_article_delete }

    ongr_oxid.relations.actions_article_old.update:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxarticles, oxarticles.OXID, oxarticles.OXID=OLD.OXARTID, product, U, 1]
