parameters:
    ongr_oxid.relations.actions_article.track_fields:
      - OXACTIONID
      - OXARTID
      - OXSORT

services:
    ongr_oxid.relations.actions_article.create:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxactions2article, C, NEW.OXARTID, 1, product, [], U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: actions_article_create }

    ongr_oxid.relations.actions_article.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxactions2article, U, NEW.OXARTID, 1, product, %ongr_oxid.relations.actions_article.track_fields%, U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: actions_article_update }
        calls:
            - [addRelation, [ @ongr_oxid.relations.actions_article_old.update ] ]

    ongr_oxid.relations.actions_article.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxactions2article, D, OLD.OXARTID, 1, product, [], U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: actions_article_delete }

    ongr_oxid.relations.actions_article_old.update:
        class: %ongr_connections.extractor.join_relation.class%
        arguments: [oxarticles, oxarticles.OXID, oxarticles.OXID=OLD.OXARTID, product, U, 1]
