parameters:
   ongr_oxid.relations.accessories.track_fields:
      - OXOBJECTID
      - OXARTICLENID
      - OXSORT

services:
    ongr_oxid.relations.accessories.create:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxaccessoire2article, C, NEW.OXARTICLENID, 1, product, [], U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: accessories_create }

    ongr_oxid.relations.accessories.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxaccessoire2article, U, NEW.OXARTICLENID, 1, product, %ongr_oxid.relations.accessories.track_fields%, U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: accessories_update }

    ongr_oxid.relations.accessories.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxaccessoire2article, D, OLD.OXARTICLENID, 1, product, [], U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: accessories_delete }

    ongr_oxid.relations.articles.update.accessories_articles:
        class: %ongr_connections.extractor.join_relation.class%
        arguments: [oxaccessoire2article, oxaccessoire2article.OXARTICLENID, oxaccessoire2article.OXOBJECTID=NEW.OXID, product, U, 1]
