parameters:
    ongr_oxid.triggers.shop_field.track_fields:
      - OXARTID
      - OXSHOPID
      - OXPRICE
      - OXFREESHIPPING
      - OXVAT
      - OXTPRICE

services:
    ongr_oxid.triggers.shop_field.create:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxfield2shop, C, 1, product, NEW.OXARTID, [], U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: shop_field_create }

    ongr_oxid.triggers.shop_field.delete:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxfield2shop, D, 1, product, OLD.OXARTID, [], U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: shop_field_delete }

    ongr_oxid.triggers.shop_field.update:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxfield2shop, U, 1, product, OLD.OXARTID, %ongr_oxid.triggers.shop_field.track_fields%]
        tags:
          - { name: ongr_connections.sql_relation, trigger: shop_field_update }
