parameters:
    ongr_oxid.relations.shop_field.track_fields:
      - OXARTID
      - OXSHOPID
      - OXPRICE
      - OXFREESHIPPING
      - OXVAT
      - OXTPRICE

services:
    ongr_oxid.relations.shop_field.create:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxfield2shop, C, NEW.OXARTID, 1, product, [], U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: shop_field_create }

    ongr_oxid.relations.shop_field.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxfield2shop, D, OLD.OXARTID, 1, product, [], U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: shop_field_delete }

    ongr_oxid.relations.shop_field.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxfield2shop, U, OLD.OXARTID, 1, product, %ongr_oxid.relations.shop_field.track_fields%]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: shop_field_update }
