parameters:
    ongr_oxid.relations.action_article.track_fields:
      - OXACTIONID
      - OXOBJECTID
      - OXCLASS

services:
    ongr_oxid.relations.action_article.create:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxobject2action, C, NEW.OXOBJECTID, 1, product, [], U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: action_article_create }

    ongr_oxid.relations.action_article.delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxobject2action, D, OLD.OXOBJECTID, 1, product, [], U]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: action_article_delete }

    ongr_oxid.relations.action_article.update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxobject2action, U, OLD.OXOBJECTID, 1, product, %ongr_oxid.relations.action_article.track_fields%]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: action_article_update }
