parameters:
    ongr_oxid.relations.articles.track_fields:
      - OXACTIVE
      - OXARTNUM
      - OXMPN
      - OXTITLE
      - OXSHORTDESC
      - OXPRICE
      - OXTPRICE
      - OXPARENTID
      - OXSTOCK
      - OXSTOCKFLAG

services:
    # Articles relations
    ongr_oxid.relations.oxarticles_insert:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxarticles, C, NEW.OXID, 1, product]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: oxarticles_insert }

    ongr_oxid.relations.oxarticles_update:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxarticles, U, NEW.OXID, 1, product, %ongr_oxid.relations.articles.track_fields%]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: oxarticles_update }
        calls:
            - [ addRelation, [ @ongr_oxid.relations.articles.update.accessories_articles2 ] ]

    ongr_oxid.relations.oxarticles_delete:
        class: %ongr_connections.extractor.descriptor.class%
        arguments: [oxarticles, D, OLD.OXID, 1, product]
        tags:
          - { name: ongr_connections.extraction_descriptor, trigger: oxarticles_delete }

    ongr_oxid.relations.articles.update.accessories_articles2:
        class: %ongr_connections.extractor.join_relation.class%
        arguments: [oxaccessoire2article, oxaccessoire2article.OXARTICLENID, oxaccessoire2article.OXOBJECTID=NEW.OXID, product, U, 1]
