parameters:
    ongr_oxid.triggers.articles.track_fields:
      - OXACTIVE
      - OXARTNUM
      - OXMPN
      - OXTITLE
      - OXSHORTDESC
      - OXPRICE
      - OXTPRICE
      - OXPARENTID
      - OXSTOCK
      - OXSTOCKFLAG

services:
    # Articles triggers
    ongr_oxid.triggers.oxarticles_insert:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxarticles, C, 1, product, NEW.OXID]
        tags:
          - { name: ongr_connections.sql_relation, trigger: oxarticles_insert }

    ongr_oxid.triggers.oxarticles_update:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxarticles, U, 1, product, NEW.OXID, %ongr_oxid.triggers.articles.track_fields%]
        tags:
          - { name: ongr_connections.sql_relation, trigger: oxarticles_update }
        calls:
            - [ addStatement, [ @ongr_oxid.triggers.articles.update.accessories_articles2 ] ]

    ongr_oxid.triggers.oxarticles_delete:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxarticles, D, 1, product, OLD.OXID]
        tags:
          - { name: ongr_connections.sql_relation, trigger: oxarticles_delete }

    ongr_oxid.triggers.articles.update.accessories_articles2:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxaccessoire2article, oxaccessoire2article.OXARTICLENID, oxaccessoire2article.OXOBJECTID=NEW.OXID, product, U, 1]
