parameters:
   ongr_oxid.triggers.accessories.track_fields:
      - OXOBJECTID
      - OXARTICLENID
      - OXSORT

services:
    ongr_oxid.triggers.accessories.create:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxaccessoire2article, C, 1, product, NEW.OXARTICLENID, [], U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: accessories_create }

    ongr_oxid.triggers.accessories.update:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxaccessoire2article, U, 1, product, NEW.OXARTICLENID, %ongr_oxid.triggers.accessories.track_fields%, U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: accessories_update }

    ongr_oxid.triggers.accessories.delete:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxaccessoire2article, D, 1, product, OLD.OXARTICLENID, [], U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: accessories_delete }

    ongr_oxid.triggers.articles.update.accessories_articles:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxaccessoire2article, oxaccessoire2article.OXARTICLENID, oxaccessoire2article.OXOBJECTID=NEW.OXID, product, U, 1]
